### ISSUE TITLE
[HumHub]Fetch fails on offline members

### ISSUE THREAD

**Issue by ArchBlood** [evnix/freichat-integrations#1]
Looking over everything the module is implemented very well, the only issue is that it doesn't fetch offline users very well so conversations between members are kind of lost in between online & offline members of a community, not only this but would also seem that once someone is set to online the chat module keeps them as online, I'm guessing this is to keep conversations from being deleted by session expired?

# Edit:
After some working, I'd suggest looking over the [Online users](https://github.com/001101/humhub-module-onlineusers) module for a possible fix for this issue.

**Comment by adeshrd** [comment]
Hi,

It does fetch offline users if you have made a conversation with them otherwise fetching offline users can put a load on the server when there are millions of them.

It treats the users as online for a few minutes and then after some inactivity it makes them offline.
We will have a look at the module you suggested, thanks.

PS: We do not check GitHub issues often, so please email any queries on admin@codologic.com

**Comment by evnix** [comment]
Hi,

It does fetch offline users if you have made a conversation with them otherwise fetching offline users can put a load on the server when there are millions of them.
Edit: You can always search for all users using the search box if you ever want to start a conversation with an offline user.

It treats the users as online for a few minutes and then after some inactivity, it makes them offline.
We will have a look at the module you suggested, thanks.

PS: We do not check GitHub issues often, so please email any queries on admin@codologic.com
